name: Node.js CI

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with: 
          fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' # You can specify any version you prefer

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Get Next Version
      id: semver
      uses: ietf-tools/semver-action@v1
      with:
        token: ${{ github.token }}
        branch: main
        noVersionBumpBehavior: current

    - name: Check if Versions are Equal
      id: check_versions
      run: |
        echo newVersion=$(test '${{ steps.semver.outputs.next }}' == '${{ steps.semver.outputs.current }}'; echo $?) >> $GITHUB_ENV

#    - name: Build
#      run: npm run build

    - name: log newly committed messages
      env:
        BEFORE_REF: ${{ github.event.before }}
        AFTER_REF: ${{ github.event.after }}
      run: git log --pretty=format:%s "$BEFORE_REF...$AFTER_REF"

    - name: Create Release
      if: ${{ env.newVersion }} != '0'
      uses: ncipollo/release-action@v1.12.0
      with:
        allowUpdates: true
        tag: ${{ steps.semver.outputs.next }}
        draft: false
        makeLatest: true
        name: Release ${{ steps.semver.outputs.next }}
        body: Changelog Contents
        token: ${{ github.token }}

    - name: Update tag version
      run: |
        git tag ${{ steps.semver.outputs.next }}
        git push origin ${{ steps.semver.outputs.next }}