name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' # You can specify any version you prefer

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Get Next Version
      id: semver
      uses: ietf-tools/semver-action@v1
      with:
        token: ${{ github.token }}
        branch: main
        noVersionBumpBehavior: current

    - name: Check if Versions are Equal
      run: |
        if [[ "${{ steps.semver.outputs.next }}" == "${{ steps.semver.outputs.current }}" ]]; then
          echo "Versions are equal. Add your action here."
        else
          echo "Versions are not equal."
        fi

    - name: Build
      run: npm run build

    - name: Create Release
      uses: ncipollo/release-action@v1.12.0
      with:
        allowUpdates: true
        draft: false
        makeLatest: true
        name: ${{ steps.semver.outputs.next }}
        body: Changelog Contents
        token: ${{ github.token }}
